### PR TITLE
Python and Go enhancements

### PR DESCRIPTION
**Pull request by pkazmier**
I tried to keep these PRs separate, but clearly I have no idea what I'm doing tonight :-) Sorry about that.

## Python Enhancements:
Here are a two enhancements to improve the theme when coding in Python. Specifically, prior to the change, there was no syntax highlighting of function or method invocations. These changes were added without impacting the syntax highlighting of javascript (per your guidance). I added a test file (per your guidance), which is a simple utility I wrote many many years ago.

Before changes:
screen shot 2018-02-02 at 7 20 28 pm

After changes:
screen shot 2018-02-02 at 7 20 41 pm

## Go Lang Enhancements:
Here are enhancements to improve the theme when coding in GoLang. Specifically, prior to the change, there was an over abundance of Sunglo Red as the "keyword" scope was too broad for a language such as Go. I added more specific "keyword" scopes (without referring to Go) to help balance and honor the intent of the theme as used with Javascript. Specifically, the keywords const, var, struct, interface, function, and type are now Cornflower Blue. These changes were added without impacting the syntax highlighting of javascript (per your guidance). I also added a test file (per your guidance), which is my first ever Go program written after reading chapter 1 of the Go Programming Book (in other words, don't judge me by that code).

Before changes:
screen shot 2018-02-02 at 8 17 06 pm

After changes:
screen shot 2018-02-02 at 8 17 17 pm

### CODE REVIEW

**Comment by will-stone** [comment]
Thanks. I'm confused as to why there's Python changes in here. Did you just want to merge you python and Go changes into one? Then I'll review their impact. Thanks.

**Comment by pkazmier** [comment]
Yeah, somehow I submitted both Python and Go changes together in one PR. Merge this one and it makes improvements for both languages. The Python changes are really small (2 lines), and the Go changes are only a few more. I took screenshots of before and after. I also confirmed that javascript was not impacted in any way. Thanks.

**Comment by will-stone** [comment]
Would you like to close the redundant pull? I'll review these changes now.

**Comment by pkazmier** [comment]
The redundant PR is closed. Thanks!

**Pull request merged**
