### PR TITLE
updated terminal colors

### PR DESCRIPTION
**Pull request by kinghat**
minor change of `bright_blue` and `bright_green` to align with the rest of the theme via the standard theme palette: issue #34 

image
image

### CODE REVIEW

**Comment by will-stone** [comment]
Hi, thanks for the PR. I'm not sure I understand this though; you've now set the standard and bright terminal blue and green colours to be the same. Maybe it would suit more if you change your terminal theme's colour variable used for your prompt and path?

**Comment by kinghat** [comment]
> Hi, thanks for the PR. I'm not sure I understand this though; you've now set the standard and bright terminal blue and green colours to be the same. Maybe it would suit more if you change your terminal theme's colour variable used for your prompt and path?

i did that so i wasnt adding or changing the color palette you have chosen but i dont think the `bright_green` and `azure_radiance` really fit and are a bit jarring. if i change those variables then wouldnt that jack with how other themes want those variables to be styled as well?

i can come up with completely different colors for these terminal variables if you would like? your take on what they could transition to might be best.

**Comment by will-stone** [comment]
Sorry, I mean I think you want to update _your_ terminal prompt, what is it? bash? zsh?. For example, I use Fish Shell and have my own prompt: https://github.com/will-stone/impure/blob/master/functions/fish_prompt.fish#L2

**Comment by kinghat** [comment]
> Sorry, I mean I think you want to update _your_ terminal prompt, what is it? bash? zsh?. For example, I use Fish Shell and have my own prompt: https://github.com/will-stone/impure/blob/master/functions/fish_prompt.fish#L2

i use bash. i knew you were talking about my local shell, i just dont see how that wouldnt affect other themes and the colors they have configured for those variables? sorry for being dense about this.

**Comment by will-stone** [comment]
I've not used Bash in quite some time, and have never tried to customise it, however I found this website which might help: http://ezprompt.net/

**Comment by will-stone** [comment]
Also this article is quite comprehensive: https://www.ibm.com/developerworks/linux/library/l-tip-prompt/

**Comment by kinghat** [comment]
> I've not used Bash in quite some time, and have never tried to customise it, however I found this website which might help: http://ezprompt.net/

> Also this article is quite comprehensive: https://www.ibm.com/developerworks/linux/library/l-tip-prompt/

thanks for the links @will-stone. i already have a terminal theme setup to match my desktop theme "Materia":

image

if you dont think `bright_green` and `azure_radiance` need adjusting to fit the theme better, thats fine,  ill just close the PR.

**Comment by will-stone** [comment]
I'm happy to see suggestions for Bright Green and Bright Blue, but they must be brighter versions than Normal Green and Normal Blue.

**Comment by kinghat** [comment]
> I'm happy to see suggestions for Bright Green and Bright Blue, but they must be brighter versions than Normal Green and Normal Blue.

`bright_blue` and `bright_green` colors are adjusted. not sure if this is a solid compromise or not?

**Comment by will-stone** [comment]
Run `./samples/terminal-colours.sh` to see this for yourself. "jump" is in the Bright variation.

Yours:
image

Original:
image

Which do you reckon is better? I think we may run the risk of washing-out the Bright colours if we lighten them all.

PS, remember to use the [name-that-color](http://chir.ag/projects/name-that-color/#CBFDAA) website to name the variables.

**Comment by kinghat** [comment]
> Run `./samples/terminal-colours.sh` to see this for yourself. "jump" is in the Bright variation.
> 
> Yours:
> image
> 
> Original:
> image
> Which do you reckon is better?

i personally think mine look better. am open to change them further. the bright colors selected in the original look like they are from a material palette in production. they just dont fit the nice color palette youve selected for the rest of the theme.

> I think we may run the risk of washing-out the Bright colours if we lighten them all.

i only want to lighten those two variables in the terminal and from what i can tell thats the only place they are used in the theme.

**Comment by kinghat** [comment]
how do you feel about this more subtle change?

original:

image

updated:

image

**Comment by will-stone** [comment]
Oooo, nice. I'll take a proper look soon and get back to you.

**Comment by will-stone** [comment]
I'm trying them out in my terminal today. Like it so far 😄

**Comment by will-stone** [comment]
I kept the colours in my terminal all yesterday. I feel it needs a little more green. Howabout Atlantis `#69c52e`?

I'm also thinking Bright Yellow should be Rob Roy `#E9D16C`; seeing as Bright Red is the same colour as Error, I feel Bright Yellow should be the same colour as Warning.

image

**Comment by kinghat** [comment]
:ok_hand: updated the PR for the color changes.

**Comment by will-stone** [comment]
Published. Thanks for the contribution.

**Comment by kinghat** [comment]
im new to the dev thing and contributing. thanks for you patience!

**Pull request merged**
